<?php
namespace Juzdy\Http\Router;

use Psr\Container\ContainerInterface;
use Juzdy\Config\Config;
use Juzdy\Config\ConfigInterface;
use Juzdy\Http\Exception\NotFoundException;
use Juzdy\Http\HandlerInterface;
use Juzdy\Http\Middleware\MiddlewareInterface;
use Juzdy\Http\MiddlewareAwareInterface;
use Juzdy\Http\RequestInterface;
use Juzdy\Http\ResponseInterface;


class DynaRouter implements RouterInterface
{

    public function __construct(private ConfigInterface $config, private ContainerInterface $container)
    {
    }

    
    private function getConfig(): ConfigInterface
    {
        return $this->config;
    }

    /**
     * Process an incoming HTTP request and dispatch it to the appropriate handler.
     *
     * @param RequestInterface $request The incoming HTTP request.
     * @param HandlerInterface $handler The next handler in the middleware chain.
     * @return ResponseInterface The HTTP response generated by the handler.
     */
    public function process(RequestInterface $request, HandlerInterface $handler): ResponseInterface
    {
        try {
            return $this->dispatch($request);
        } catch (NotFoundException $e) {
            // Let the next middleware/handler process the request
        }
        
        return $handler->handle($request);
    }

    /**
     * Convert a handler class name to a route string.
     *
     * @param string $handlerClass The fully qualified handler class name.
     * @return string The corresponding route string.
     */
    public static function route(string $handlerClass): string
    {
        //$class = str_replace(, '', $handlerClass);

        $parts = preg_split('/(?=[A-Z])/', $handlerClass, -1, PREG_SPLIT_NO_EMPTY);
        $routeParts = [];
        foreach ($parts as $part) {
            $routeParts[] = strtolower(preg_replace('/([a-z])([A-Z])/', '$1-$2', $part));
        }
        return implode('/', $routeParts);
    }

    

    /**
     * Dispatch a route to the appropriate controller/action.
     * e.g. 'account/profile' -> \App\Controller\Account\ProfileController
     */
    private function dispatch(RequestInterface $request): ResponseInterface
    {
        $route = $request->query($this->getConfig()->get('http.htaccess_handler_rewrite_param') ?? uniqid()) ?? '';

        $parts = array_filter(explode('/', $route));

        if (count($parts) < 1) {
            $parts[] = $this->getConfig()->get('http.default_handler') ?? 'index'; // Default handler if not specified
        }
        
        // Convert kebab-case to camelCase for each part
        $parts = array_map(function($part) {
            return preg_replace_callback('/-([a-z])/', function($matches) {
                return strtoupper($matches[1]);
            }, $part);
        }, $parts);
        
        // Build the fully qualified class name
        $route = implode('\\', array_map('ucfirst', $parts));
        // Remove underscores for class names
        $route = str_replace('_', '', $route); 

        $handlerClass = $this->resolveHandlerClass($route);

        if (!class_exists($handlerClass) || !is_subclass_of($handlerClass, HandlerInterface::class)) {
                throw new \RuntimeException("Handler not found: $handlerClass");
        }

        // Instantiate the handler via the container
        $handler = $this->getContainer()->get($handlerClass);
        
        // Apply middleware group to controller if applicable
        $this->applyMiddlewareGroup($handler);
        
        // Execute controller with its middleware
        return $handler->executeWithMiddleware(function() use ($handler, $request) {
            return $handler->handle($request);
        }, $request);
    }

    /**
     * Resolve a handler class from a route using composer namespaces.
     *
     * @param string $route
     * @return string
     */
    private function resolveHandlerClass(string $route): string
    {
        $handlerClasses = $this->resolveHandlerClassesFromComposer($route);

        if (count($handlerClasses) === 0) {
            throw new NotFoundException("Handler not found for route: $route");
        }

        if (count($handlerClasses) > 1) {
            $handlers = implode(', ', $handlerClasses);
            throw new \RuntimeException("Multiple handlers found for route: $route: $handlers");
        }

        return $handlerClasses[0];
    }

    /**
     * Find all handler classes that match a route.
     *
     * @param string $route
     * @return array<int, string>
     */
    private function resolveHandlerClassesFromComposer(string $route): array
    {
        $handlerClasses = [];

        foreach ($this->getComposerNamespaces() as $namespace) {
            foreach ($this->getConfig()->get('http.request_handlers_namespace') as $handlerNamespace) {
                $possibleHandler = preg_replace(
                    '/\\\\+/',
                    '\\',
                    str_replace('{namespace}', $namespace, $handlerNamespace) . '\\' . $route
                );

                if (class_exists($possibleHandler) && is_subclass_of($possibleHandler, HandlerInterface::class)) {
                    $handlerClasses[] = $possibleHandler;
                }
            }
        }

        return $handlerClasses;
    }

    /**
     * Get composer namespaces used for handler resolution.
     *
     * @return array<int, string>
     */
    private function getComposerNamespaces(): array
    {
        return \Juzdy\Composer\Composer::namespaces();
    }

    /**
     * Apply middleware group to a controller.
     *
     * @param HandlerInterface $handler
     * @return void
     */
    private function applyMiddlewareGroup(HandlerInterface $handler): void
    {
        $is_a = array_merge(
            [$handler::class],
            class_parents($handler),
            class_implements($handler),
        );

        foreach ($is_a as $of) {
            
            $middlewareClasses = $this->getConfig()->get("middleware.handler.{$of}") ?? [];
            
            foreach ($middlewareClasses as $middlewareClass) {
                if (!class_exists($middlewareClass)) {
                    throw new \RuntimeException("Middleware class {$middlewareClass} not found.");
                }
                
                if (!is_subclass_of($middlewareClass, MiddlewareInterface::class)) {
                    throw new \RuntimeException("Middleware class {$middlewareClass} must implement MiddlewareInterface.");
                }

                if ($handler instanceof MiddlewareAwareInterface) {
                    $handler->addMiddleware(
                        $this->getContainer()->get($middlewareClass)
                    );
                } else {
                        throw new \RuntimeException("Handler class " . get_class($handler) . " must implement MiddlewareAwareInterface to add middleware.");
                }
                
            }
        }
    }

    /**
     * Get the dependency injection container.
     *
     * @return ContainerInterface The container instance.
     */
    protected function getContainer(): ContainerInterface
    {
        return $this->container;
    }

}
