<?php
namespace Juzdy\Http\Router;

use Juzdy\App\Http\Exception\Router\RouteConflictException;
use Juzdy\App\Http\Exception\Router\RouteNotFoundException;
use Psr\Container\ContainerInterface;
use Juzdy\Config\ConfigInterface;
use Juzdy\Http\Exception\NotFoundException;
use Juzdy\Http\HandlerInterface;
use Juzdy\Http\Middleware\MiddlewareInterface;
use Juzdy\Http\MiddlewareAwareInterface;
use Juzdy\Http\RequestInterface;
use Juzdy\Http\ResponseInterface;


class DynaRouter implements RouterInterface
{

    public static ?DynaRouter $instance = null;

    public function __construct(
        private ConfigInterface $config,
        private ContainerInterface $container
    )
    {
        self::$instance = $this;
    }

    /**
     * Get the configuration instance.
     *
     * @return ConfigInterface The configuration instance.
     */
    private function getConfig(): ConfigInterface
    {
        return $this->config;
    }

    /**
     * Get the dependency injection container.
     *
     * @return ContainerInterface The container instance.
     */
    private function getContainer(): ContainerInterface
    {
        return $this->container;
    }

    /**
     * Process an incoming HTTP request and dispatch it to the appropriate handler.
     *
     * @param RequestInterface $request The incoming HTTP request.
     * @param HandlerInterface $handler The next handler in the middleware chain.
     * @return ResponseInterface The HTTP response generated by the handler.
     */
    public function process(RequestInterface $request, HandlerInterface $handler): ResponseInterface
    {
        try {
            return $this->dispatch($request);
        } catch (NotFoundException $e) {
            // Let the next middleware/handler process the request
        }
        
        return $handler->handle($request);
    }

    /**
     * Convert a handler class name to a route string.
     *
     * @param string $handlerClass The fully qualified handler class name.
     * @return string The corresponding route string.
     */
    public static function route(string $handlerClass): string
    {
        foreach (self::$instance->getConfig()->get('dynamic-router.handler-namespaces') as $handlerNamespace) {
            if (str_starts_with($handlerClass, $handlerNamespace)) {
                $relativeClass = substr($handlerClass, strlen($handlerNamespace));
                $route = str_replace('\\', '/', $relativeClass);
                // Convert camelCase to kebab-case
                $route = preg_replace('/([a-z])([A-Z])/', '$1-$2', $route);
                return '/' . strtolower($route);
            }
        }

        throw new RouteNotFoundException("Route not found for handler class: $handlerClass");
    }

    /**
     * Dispatch a route to the appropriate controller/action.
     * e.g. 'account/profile' -> \App\Controller\Account\ProfileController
     */
    private function dispatch(RequestInterface $request): ResponseInterface
    {
        $route = $request->query($this->getConfig()->get('dynamic-router.handler-query-param') ?? uniqid()) ?? '';

        $parts = array_filter(explode('/', $route));

        if (count($parts) < 1) {
            $parts[] = 'Index'; // Default handler if not specified
        }
        
        // Convert kebab-case to camelCase for each part
        $parts = array_map(function($part) {
            return preg_replace_callback('/-([a-z])/', function($matches) {
                return strtoupper($matches[1]);
            }, $part);
        }, $parts);
        
        // Build the fully qualified class name
        $route = implode('\\', array_map('ucfirst', $parts));
        // Remove underscores for class names
        $route = str_replace('_', '', $route); 

        $handlerClass = $this->resolveHandlerClass($route);

        if (!class_exists($handlerClass) || !is_subclass_of($handlerClass, HandlerInterface::class)) {
                throw new RouteNotFoundException("Handler not found: $handlerClass");
        }

        // Instantiate the handler via the container
        $handler = $this->getContainer()->get($handlerClass);
        
        // Apply middleware group to controller if applicable
        $this->applyMiddlewareGroup($handler);
        
        // Execute controller with its middleware
        return $handler->executeWithMiddleware(function() use ($handler, $request) {
            return $handler->handle($request);
        }, $request);
    }

    /**
     * Resolve a handler class from a route using composer namespaces.
     *
     * @param string $route
     * @return string
     */
    private function resolveHandlerClass(string $route): string
    {
        $handlerClasses = $this->resolveHandlerClasses($route);

        if (count($handlerClasses) === 0) {
            throw new RouteNotFoundException("Handler not found for route: $route");
        }

        if (count($handlerClasses) > 1) {
            $handlers = implode(', ', $handlerClasses);
            throw new RouteConflictException("Multiple handlers found for route: $route: $handlers");
        }

        return $handlerClasses[0];
    }

    /**
     * Find all handler classes that match a route.
     *
     * @param string $route
     * @return array<int, string>
     */
    private function resolveHandlerClasses(string $route): array
    {
        $handlerClasses = [];

        foreach ($this->getConfig()->get('dynamic-router.handler-namespaces') ?? [] as $handlerNamespace) {

            $possibleHandler = $handlerNamespace . $route;

            if (class_exists($possibleHandler) && is_subclass_of($possibleHandler, HandlerInterface::class)) {
                $handlerClasses[] = $possibleHandler;
            }
        }

        return $handlerClasses;
    }

    /**
     * Apply middleware group to a controller.
     *
     * @param HandlerInterface $handler
     * @return void
     */
    private function applyMiddlewareGroup(HandlerInterface $handler): void
    {
        $is_a = array_merge(
            [$handler::class],
            class_parents($handler),
            class_implements($handler),
        );

        foreach ($is_a as $of) {
            
            $middlewareClasses = $this->getConfig()->get("dynamic-router.handler-middleware.{$of}") ?? [];
            
            foreach ($middlewareClasses as $middlewareClass) {
                if (!class_exists($middlewareClass)) {
                    throw new \RuntimeException("Middleware class {$middlewareClass} not found.");
                }
                
                if (!is_subclass_of($middlewareClass, MiddlewareInterface::class)) {
                    throw new \RuntimeException("Middleware class {$middlewareClass} must implement MiddlewareInterface.");
                }

                if ($handler instanceof MiddlewareAwareInterface) {
                    $handler->addMiddleware(
                        $this->getContainer()->get($middlewareClass)
                    );
                } else {
                        throw new \RuntimeException("Handler class " . get_class($handler) . " must implement MiddlewareAwareInterface to add middleware.");
                }
                
            }
        }
    }

}
