<?php
/**
 ▄▄▄
  █ J █ u z d y
   ▀▀▀
 */
namespace Juzdy\Http;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Server\MiddlewareInterface;
use Juzdy\App\AppInterface;
use Juzdy\Http\Event\AfterRun;
use Juzdy\Http\Event\BeforeRun;
use Juzdy\Container\Attribute\Shared;
use Juzdy\Container\Contract\Lifecycle\SharedInterface;
use Juzdy\Container\Repository\ShareManager;
use Juzdy\Http\Middleware\AppMiddlewareStack;
use Juzdy\Http\Middleware\Proxy\MiddlewareProxyFactory;

/**
 * HTTP Application implementation
 *
 * @package Juzdy\Http
 */
// #[Prefer(
//     [
//         EventDispatcherInterface::class => \Juzdy\EventBus\EventDispatcher::class,
//     ]
// )]
#[Shared]
class Http implements AppInterface, SharedInterface
{
    /**
     * The current HTTP request being processed. 
     * This will be initialized when the application runs 
     * and can be accessed by middleware and handlers to retrieve request data.
     * @var ServerRequestInterface|null
     */
    private ?ServerRequestInterface $request = null;

    /**
     * The HTTP response generated by the middleware stack. 
     * This will be set after processing the request and can be accessed 
     * by middleware and handlers to modify or inspect the response before it is sent back to the client.
     * @var ResponseInterface|null
     */
    private ?ResponseInterface $response = null;
    
    /**
     * Http constructor.
     *
     * @param ContainerInterface        $container              The dependency injection container
     * @param AppMiddlewareStack        $appMiddlewareStack     The middleware stack
     * @param MiddlewareProxyFactory    $middlewareProxyFactory Factory for creating middleware proxies
     */    
    public function __construct(
        private ContainerInterface $container,
        private AppMiddlewareStack $appMiddlewareStack,
        private MiddlewareProxyFactory $middlewareProxyFactory,
        private ShareManager $shareManager,
    ) {
    }

    /**
     * {@inheritDoc}
     */
    public function __invoke(string $service): mixed
    {
        return $this->container->get($service);
    }

    public function share(string $service, mixed $instance): void
    {
        $this->shareManager->share($service, $instance);
    }

    /**
     * {@inheritDoc}
     */
    public function run(): void
    {   
        try {
            $this
                ->beforeRun()
                ->handleRequest()
                ->afterRun();

        } catch (\Throwable $e) {
            // @todo: handle exceptions gracefully, e.g. by returning an error response or rendering an error page
            throw $e;
            
        }   
    }

    /**
     * {@inheritDoc}
     */
    public function withMiddleware(int $priority, string|MiddlewareInterface ...$middleware): static
    {
        foreach ($middleware as $id) {
            $middleware = match(true) {
                is_string($id) => $this->middlewareProxyFactory->create($id),
                is_a($id, MiddlewareInterface::class, true) => $id,
                default => throw new \InvalidArgumentException(_('Middleware must be either a string identifier or an instance of MiddlewareInterface.')),
            };

            if (!$middleware instanceof MiddlewareInterface) {
                throw new \InvalidArgumentException(_('Middleware must be an instance of MiddlewareInterface.'));
            }

             $this->appMiddlewareStack->push($middleware, $priority);
        }

        return $this;
    }

    /**
     * Handle the incoming HTTP request and produce a response
     * by processing the middleware stack.
     *
     * @return static
     */
    protected function handleRequest(): static
    {
        $this->response = $this->appMiddlewareStack->handle($this->getRequest());

        return $this;
    }

    /**
     * Get the current HTTP request.
     *
     * @return ServerRequestInterface
     */
    protected function getRequest(): ServerRequestInterface
    {
        return $this->request ??= $this->getRequestFactory()->createServerRequest();
    }

    /**
     * Get the request factory.
     *
     * @return ServerRequestFactoryInterface
     */
    protected function getRequestFactory(): ServerRequestFactoryInterface
    {
        return $this->container->get(ServerRequestFactoryInterface::class);
    }

    /**
     * Get the current HTTP response.
     *
     * @return ResponseInterface
     */
    protected function getResponse(): ResponseInterface
    {
        if ($this->response === null) {
            // If no response has been generated by the middleware stack, create a default empty response
            $this->response = $this->container?->get(ResponseFactoryInterface::class)?->createResponse()
                ?->withStatus(204) ?? throw new \RuntimeException(_('No response has been generated yet.'));
        }

        return $this->response;
    }

    /**
     * Dispatch the before run event.
     *
     * @return static
     */
    private function beforeRun(): static
    {
        $this->container->get(BeforeRun::class)->fire(
                [
                    'app' => $this,
                    'request' => $this->getRequest(),
                ]
            );

        return $this;
    }

    /**
     * Dispatch the after run event.
     *
     * @return static
     */
    private function afterRun(): static
    {
        $this->container->get(AfterRun::class)->fire(
                [
                    'app'     => $this,
                    'request' => $this->getRequest(),
                    'response' => $this->getResponse(),
                ]
            );

        return $this;
    }
    
}